---
title: "main"
format: pdf
---

```{r, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(broom)
# Install and load the "MASS" package if not already installed
if (!require("MASS")) {
  install.packages("MASS")
  library("MASS")
}
```

```{r, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
data <- read_csv("data/bst210_project_data.csv")
subset_data_2019 <- data |>
  filter(income_level %in% c("Low income", "Lower middle income")) |> 
  filter(year == 2019)

subset_data_2019$co2_produced <- subset_data_2019$co2_per_capita * subset_data_2019$population
```

Unadjusted

```{r, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
# Without offset
under_5_unadjusted <- glm.nb(
  formula = mortality_rate_under_5 ~ co2_per_capita ,
  data = subset_data_2019
)

# Display the summary information for the model
tidy(under_5_unadjusted, exponentiate = TRUE)


```

Adjusted

```{r, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
under_5_adjusted <- glm.nb(
  formula = mortality_rate_under_5 ~ co2_per_capita + pm2_5 + gdp_per_capita + health_expenditure_percent_of_gdp + basic_sanitation + immunization,
  data = subset_data_2019
)
colnames(subset_data_2019)
# Display the summary information for the model
tidy(under_5_adjusted, exponentiate = TRUE)

```
